# Generated by Django 4.1.13 on 2024-04-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_merge_20240428_2122'),
        ('blog', '0004_post_tags'),
    ]

    operations = [
    ]
